version: '3'
services:
  datastore:
    image: busybox
    volumes:
      # - db_data:/var/lib/mysql
      # - db_data:/var/lib/postgresql/data
      - bundle_install:/usr/local/bundle
      - node_modules:/app/node_modules
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   volumes:
  #   - db_data:/var/lib/mysql
  #   env_file:
  #     - .env.dev
  #   stdin_open: true
  #   tty: true
  # db:
  #   image: postgres:12.2-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   env_file:
  #     - .env.dev
  #   stdin_open: true
  #   tty: true
  app:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile.dev
    # command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    volumes:
      - bundle_install:/usr/local/bundle
      - node_modules:/app/node_modules
      - ./:/app:cached
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
volumes:
  # db_data:
  bundle_install:
  node_modules:
